config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#welcome"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :products, only: %i[index show] do
    resources :follow_ups, only: :create
  end
  resources :follow_ups, only: %i[update destroy]
  get "/profile/:id", to: "pages#profile", as: 'profile'
  get "/profile/:id", to: "pages#add_friend", as: 'add_friend'
  get "/map", to: "pages#map", as: 'map'
  get "/export/:id", to: "pages#export", as: "export"
  get "/home", to: "pages#home"
  get "/about", to: "pages#about"
end

app/views/shared/_carousel.html.erb
<div class="container">
  <div class="swiper mySwiper my-4" data-controller="swiper">
    <div class="swiper-wrapper" data-action='click->swiper#navigate'>
    <% products.shuffle.each do |product| %>
      <div class="swiper-slide">
        <%= link_to product_path(product),
                      data: { action: 'click->swiper#navigate' },
                      class: 'card-category text-decoration-none',
                      style: "background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(#{cl_image_path product.photo.key, :height=>300, :quality=>"50", :width=>300, :crop=>"fill"})" do %>
            <p><%= product.name.capitalize %></p>
          <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_grades.html.erb
<div class="d-flex justify-content-evenly py-3">
    <% if score.nil? %>
      <div class="d-none"></div>
    <% else %>
      <div class="set-size charts-container">
        <div class="pie-wrapper progress-<%= score %> style-2">
          <span class="label"><%= score %><span class="smaller"></span></span>
            <div class="pie">
              <div class="left-side half-circle"></div>
              <div class="right-side half-circle"></div>
            </div>
          <div class="shadow"></div>
        </div>
      </div>

      <div>
        <ul class="list-unstyled grade-scale-profile">
          <li>
            <% if note == 'A' %>
              <p><span class="grade-a">A</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-a">A</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'B' %>
              <p><span class="grade-b">B</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-b">B</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'C' %>
              <p><span class="grade-c">C</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-c">C</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'D' %>
              <p><span class="grade-d">D</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-d">D</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'E' %>
              <p><span class="grade-e">E</span><i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-e">E</span></p>
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>


  </div>

  <% unless score.nil? %>
    <% if score < 20 %>
      <h6 class="comment-score">Aïe, allez on vous aide.</h6>
      <p>Voici les fruits et légumes du mois: <br><%= link_to ('<i class="fa-solid fa-seedling icon-link-score"></i>').html_safe, products_path %> !</p>
    <% elsif score >= 20 && score < 40%>
      <h6 class="comment-score">Encore un petit peu d'effort !</h6>
      <p>Suivez les fruits et légumes du mois ici: <br><br><%= link_to ('<i class="fa-solid fa-seedling icon-link-score"></i>').html_safe, products_path %></p>
    <% elsif score >= 40 && score < 60 %>
      <h6 class="comment-score">C'est de mieux en mieux !</h6>
      <p>Continuez sur cette lancée en vous aidant de notre guide: <br><br><%= link_to ('<i class="fa-solid fa-seedling icon-link-score"></i>').html_safe, products_path %></p>
    <% elsif score >= 60 && score < 80 %>
      <h6 class="comment-score">Bravo, vous êtes à quelques pas du but !</h6>
      <p>Aidez-vous de notre guide des produits du moment: <br><br><%= link_to ('<i class="fa-solid fa-seedling icon-link-score"></i>').html_safe, products_path %></p>
    <% elsif score <= 100 %>
      <h6 class="comment-score">Génial, vos petits gestes ont de grands impacts !</h6>
      <p>Surpassez vous encore, et aller voir les produits du mois: <br><br><%= link_to ('<i class="fa-solid fa-seedling icon-link-score"></i>').html_safe, products_path %></p>
    <% end %>
  <% end %>

app/views/shared/_grades_global.html.erb
<div>
  <div class="d-flex justify-content-evenly py-3">
    <% if score.nil? %>
      <div class="d-none"></div>
    <% else %>
      <%= image_tag 'little-stick.svg', class: "stick-bottom" %>
      <%= image_tag 'little-stick-top.svg', class: "stick-top" %>

      <figure class="progress-score-user" data-controller="countup">
        <figcaption style="--color: <%= color(score) %>" id="score-global" data-countup-target="score"><%= score %></figcaption>
        <svg viewBox="0 0 63.6619772368 63.6619772368" style="--color: <%= color(score) %>">
          <circle class="pie1" style="--c: <%= score %>; --m: <%= 100 - score %>; --color: <%= color(score) %>" cx="31.8309886184" cy="31.8309886184" r="15.9154943092"/>
        </svg>
      </figure>

      <div>
        <ul class="list-unstyled grade-scale-profile">
          <li>
            <% if note == 'A' %>
              <p><span class="grade-a">A</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-a">A</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'B' %>
              <p><span class="grade-b">B</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-b">B</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'C' %>
              <p><span class="grade-c">C</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-c">C</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'D' %>
              <p><span class="grade-d">D</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-d">D</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'E' %>
              <p><span class="grade-e">E</span><i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-e">E</span></p>
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>
<p class="about-score">En savoir plus sur le <%= link_to 'score', about_path  %></p>

  <% if current_user == @user %>
    <div class="motivation-speech" style="background-image: url(<%= image_path('shape-round.svg') %>)">
      <%= image_tag 'various_fruits.svg', class: 'pt-5' %>
      <div class="motivation-content">
        <% unless score.nil? %>
          <% if score < 20 %>
            <h6 class="comment-score">Aïe, allez on vous aide.</h6>
            <p>Voici les <%= link_to 'fruits et légumes', products_path, class: 'link-from-profile' %> du mois.
          <% elsif score >= 20 && score < 40%>
            <h6 class="comment-score">Encore un petit peu d'effort !</h6>
            <p>Suivez les fruits et légumes du mois <%= link_to 'ici', products_path, class: 'link-from-profile' %>.
          <% elsif score >= 40 && score < 60 %>
            <h6 class="comment-score">C'est de mieux en mieux !</h6>
            <p>Continuez sur cette lancée en vous aidant de notre <%= link_to 'guide', products_path, class: 'link-from-profile' %>.
          <% elsif score >= 60 && score < 80 %>
            <h6 class="comment-score">Bravo, vous êtes à quelques pas du but !</h6>
            <p>Aidez-vous de notre <%= link_to 'guide', products_path, class: 'link-from-profile' %> des produits du moment.
          <% elsif score <= 100 %>
            <h6 class="comment-score">Génial, vos petits gestes ont de grands impacts !</h6>
          <p>Surpassez vous encore, et aller voir les <%= link_to 'produits du mois', products_path, class: 'link-from-profile' %>. </p>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/shared/_grades_month.html.erb
 <div>
  <div class="d-flex justify-content-evenly py-3">
    <% if score.nil? %>
      <div class="d-none"></div>
    <% else %>
      <%= image_tag 'little-stick.svg', class: "stick-bottom" %>
      <%= image_tag 'little-stick-top.svg', class: "stick-top" %>
      <figure class="progress-score-user" data-controller="countup-month">
        <figcaption style="--color: <%= color(score) %>" id="score-month" data-countup-month-target="scoreMonth"><%= score %></figcaption>
        <svg viewBox="0 0 63.6619772368 63.6619772368" style="--color: <%= color(score) %>">
          <circle class="pie1" style="--c: <%= score %>; --m: <%= 100 - score %>; --color: <%= color(score) %>" cx="31.8309886184" cy="31.8309886184" r="15.9154943092"/>
        </svg>
      </figure>

      <div>
        <ul class="list-unstyled grade-scale-profile">
          <li>
            <% if note == 'A' %>
              <p><span class="grade-a">A</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-a">A</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'B' %>
              <p><span class="grade-b">B</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-b">B</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'C' %>
              <p><span class="grade-c">C</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-c">C</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'D' %>
              <p><span class="grade-d">D</span> <i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-d">D</span></p>
            <% end %>
          </li>
          <li>
            <% if note == 'E' %>
              <p><span class="grade-e">E</span><i class="fa-solid fa-caret-left fa-xs grade-indicator"></i></p>
            <% else %>
              <p><span class="grade-e">E</span></p>
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>
<% unless export %>
  <p class="about-score">En savoir plus sur le <%= link_to 'score', about_path  %></p>
<% end %>

  <div class="motivation-speech" style="background-image: url(<%= image_path('shape-round.svg') %>)">
    <%= image_tag 'various_fruits.svg', class: 'pt-5' %>
    <div class="motivation-content">
      <% unless score.nil? %>
        <% if score < 20 %>
          <h6 class="comment-score">Aïe, allez on vous aide.</h6>
          <p>Voici les <%= link_to 'fruits et légumes', products_path, class: 'link-from-profile' %> du mois.
        <% elsif score >= 20 && score < 40%>
          <h6 class="comment-score">Encore un petit peu d'effort !</h6>
          <p>Suivez les fruits et légumes du mois <%= link_to 'ici', products_path, class: 'link-from-profile' %>.
        <% elsif score >= 40 && score < 60 %>
          <h6 class="comment-score">C'est de mieux en mieux !</h6>
          <p>Continuez sur cette lancée en vous aidant de notre <%= link_to 'guide', products_path, class: 'link-from-profile' %>.
        <% elsif score >= 60 && score < 80 %>
          <h6 class="comment-score">Bravo, vous êtes à quelques pas du but !</h6>
          <p>Aidez-vous de notre <%= link_to 'guide', products_path, class: 'link-from-profile' %> des produits du moment.
        <% elsif score <= 100 %>
          <h6 class="comment-score">Génial, vos petits gestes ont de grands impacts !</h6>
          <p>Surpassez vous encore, et aller voir les <%= link_to 'produits du mois', products_path, class: 'link-from-profile' %>. </p>
        <% end %>
      <% end %>
    </div>
  </div>


<% if current_user == @user && !export %>
  <% colors = ['#0B8790', '#90DBD0', '#FDCB44', '#FDB3A5', '#FC755D', '#FDE773'] %>
  <% unless user.follow_ups.nil? %>
    <div>
      <% @month_fo_product.each do |fo| %>
        <div class="card card-edit-follow-up my-3" style="border-color: <%= colors.sample.html_safe %>">
          <div class="d-flex justify-content-between">
            <div>
              <%= cl_image_tag fo.product.photo.key, :height=>300, :quality=>"50", :width=>300, :crop=>"fill", overflow: 'hidden', class: 'card-image-follow-up' %>
            </div>

            <div class="d-flex justify-content-between flex-grow-1">
              <div class="follow-up-info">
              <h2 class="pt-3" style="color: <%= colors.sample.html_safe %>">
              <%= link_to fo.product.name.titleize, fo.product, class: "d-block mb-3 text-decoration-none", style: "color: #{colors.sample}"%></h2>
              <p class="add-date"><i>Ajouté le <span><%= (l fo.created_at, format: '%-d %B') %></span></i></p>
                <div class="d-grid info-product-fo">
                  <% if fo.product.season?(@month) %>
                    <p><span>Saison <i class="fa-solid fa-check fa-sm card-check"></i></span></p>
                  <% else  %>
                    <p><span>Saison <i class="fa-solid fa-xmark fa-sm card-cross"></i></span></p>
                  <% end %>

                  <% if fo.local %>
                    <p class="card-info-check"><span>Local <i class="fa-solid fa-check fa-sm card-check"></i></span></p>
                  <% else  %>
                    <p class="card-info-check"><span>Local <i class="fa-solid fa-xmark fa-sm card-cross"></i></span></p>
                  <% end %>

                  <% if fo.bio %>
                    <p class="card-info-check"><span>Bio <i class="fa-solid fa-check fa-sm card-check"></i></span></p>
                  <% else  %>
                    <p class="card-info-check"><span>Bio <i class="fa-solid fa-xmark fa-sm card-cross"></i></span></p>
                  <% end %>
                </div>
              </div>

              <div class="d-grid pt-3 pe-4">
                <!-- Button trigger modal -->
                <button type="button" class="btn button-edit-modal" data-bs-toggle="modal" data-bs-target="#exampleModal<%= fo.id %>">
                  <i class="fa-solid fa-pen-to-square fa-sm"></i>
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal<%= fo.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title modal-edit-title" id="exampleModalLabel" style="color: <%= colors.sample.html_safe %>"><%= fo.product.name.titleize %></h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                        <%= simple_form_for fo do |f| %>
                          <div class="modal-body">
                            <div class="container">
                              <div class="h-100">
                                <% if fo.product.localable %>
                                  <%= f.input :local, as: :boolean, label: 'Votre produit est&nbsp<strong>français</strong>'.html_safe, input_html: { class: "toggle d-none", id: "product-local#{fo.id}" }, label_html: { for: "product-local#{fo.id}"} %>
                                <% else %>
                                  <%= f.input :local, as: :boolean, disabled: true, label: "Votre produit n'est pas&nbsp<strong>français</strong>".html_safe, input_html: { class: "toggle d-none"} %>
                                <% end %>
                                <%= f.input :bio, as: :boolean, label: 'Votre produit est&nbsp<strong>bio</strong>'.html_safe, input_html: { class: "toggle d-none", id: "product-bio#{fo.id}"}, label_html: { for: "product-bio#{fo.id}"} %>
                              </div>
                            </div>
                          </div>
                          <div class="modal-footer">
                            <%= f.submit 'Enregistrer', class: 'btn btn-primary', style: 'color: white' %>
                          </div>
                        <% end %>
                    </div>
                  </div>
                </div>

                <%= link_to ('<i class="fa-solid fa-trash-can fa-sm"></i>').html_safe, follow_up_path(fo), data: { turbo_method: 'delete' }, class: 'button-delete-modal' %>

              </div>
            </div>
          </div>

        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_last_score.html.erb
  <% unless last.nil? %>
    <% if last < 20 %>
      <p>Votre score du mois de <%= last_m %> <br><i class="fa-solid fa-circle fa-2xs grade-e"></i> <%= last %> points</p>
    <% elsif last >= 20 && last < 40%>
      <p>Votre score du mois de <%= last_m %> <br><i class="fa-solid fa-circle fa-2xs grade-d"></i> <%= last %> points</p>
    <% elsif last >= 40 && last < 60 %>
      <p>Votre score du mois de <%= last_m %> <br><i class="fa-solid fa-circle fa-2xs grade-c"></i> <%= last %> points</p>
    <% elsif last >= 60 && last < 80 %>
      <p>Votre score du mois de <%= last_m %> <br><i class="fa-solid fa-circle fa-2xs grade-b"></i> <%= last %> points</p>
    <% elsif last <= 100 %>
      <p>Votre score du mois de <%= last_m %> <br><i class="fa-solid fa-circle fa-2xs grade-a"></i> <%= last %> points</p>
    <% end %>
  <% end %>

app/views/shared/_modal.html.erb
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->

<% @stores['records'].each do |store| %>
  <div class="modal fade" id="store-modal-<%= store.recordid %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%  @products_all = Product.pluck(:name) %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-image: url('<%= image_url('navbar-background.svg')%>');background-repeat: no-repeat" >
  <div class="container">
    <% if params[:action] == "home" || params[:action] == "export" %>
      <%= link_to home_path, class: "navbar-brand" do %>
        <%# Tutti Frutti <i class="fa-solid fa-seedling"></i> %>
        <span style="padding-bottom: 10px;">Tutti Frutti</span>
        <%= image_tag 'new_logo.png', class: 'image-logo-navbar' %>
      <% end %>
      <% elsif params[:action] != "export" %>
          <div class="navbar-brand-else" data-controller="search-complete" data-search-complete-source-value="<%= @products_all %>">
            <div class="search-box-navbar" data-controller="search-button">
              <button name="button" class="btn-search-navbar" data-action = "click->search-button#displaySearchBar"><i class="fas fa-search"></i></button>
              <%= form_tag products_path, method: :get do |f| %>
                  <button name="button" type="submit" class="d-none" data-search-button-target="submit"><i class="fas fa-search"></i></button>
                  <%= text_field_tag :query, params[:query], data: { 'search-button-target' => 'input', 'search-complete-target' => 'query', 'action' => 'focusout->search-button#closeSearchBar' }, class: "form-control string required input-search-navbar rounded", id: "search_query", placeholder: "Haricot", style: "color: white" %>
              <% end  %>
            </div>
            <%= link_to home_path do %>
              <%= image_tag 'new_logo.png', class: 'image-logo-navbar' %>
            <% end %>
          </div>
      <% end %>
    <% if params[:action] != "export" %>

    <input id="toggle" type="checkbox" class="d-none"/>
    <label class="hamburger" for="toggle" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <div class="top"></div>
      <div class="meat"></div>
      <div class="bottom"></div>
    </label>

    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto d-flex flex-col align-items-end" >
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= link_to "Mon profil", profile_path(current_user), class: "dropdown-item dropdown-item-first" %>
            <%= link_to "Où acheter ?", map_path, class: "dropdown-item" %>
            <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item dropdown-item-last" %>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item text-end dropdown-item-first" %>
            <%= link_to "Où acheter ?", map_path, class: "dropdown-item text-end dropdown-item-last"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% end %>

  <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar" %>
  <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
  <%# <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
  </div> %>

app/views/shared/_search_form.html.erb
<%  @products_all = Product.pluck(:name) %>
<%= form_tag products_path, class: "simple_form_home search rounded", method: :get do |f| %>
  <div class="search-form-control form-group my-3" data-controller="search-complete" data-search-complete-source-value="<%= @products_all %>">
    <div class="form-search search-data">
    <%= text_field_tag :query, params[:query], data: { 'search-complete-target' => 'query' }, autocomplete: :off, class: "form-control form-control-search-homepage string required bg-light", placeholder: 'Fraise' %>
    <button name="button" type="submit" class="btn btn-flat d-flex justify-content-center align-items-center">
      <i class="fas fa-search"></i>
    </button>
  </div>
<% end %>