config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#welcome"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :products, only: %i[index show] do
    resources :follow_ups, only: :create
  end
  resources :follow_ups, only: %i[update destroy]
  get "/profile/:id", to: "pages#profile", as: 'profile'
  get "/profile/:id", to: "pages#add_friend", as: 'add_friend'
  get "/map", to: "pages#map", as: 'map'
  get "/export/:id", to: "pages#export", as: "export"
  get "/home", to: "pages#home"
  get "/about", to: "pages#about"
end

app/views/pages/about.html.erb
<title><% content_for :title, "Tutti Frutti - Tout comprendre sur votre score" %></title>

<div class="container" style="height: 100vh; background-image: url('<%= image_url('lemon.svg')%>'); background-repeat: no-repeat; background-position: right center; background-size: contain;">
  <div class="row justify-content-center m-2">
    <div class="col-sm-8 m-2">
      <div class="text-justify my-2 align-items-justify highlight-title">
        <h6>Comment est calculé votre score ?</h6>
        <p> Notre méthodologie est <strong>simple et pragmatique</strong>.</p>
        <p>Seuls 3 critères sont pris en compte afin de calculer un <strong>score sur 100 points</strong>.</p>
        <ul>
      </div>
    </div>
  </div>

  <div class="text-justify my-2 align-items-justify highlight-title" >
    <ol>
      <li><p>La saison du produit : c'est le critère le plus important. Si vous ne deviez en retenir qu'un ce serait celui là. <br><strong>75 points</strong>.</p></li>
      <li><p>La provenance du produit : il est préférable de consommer local. Choisir un produit français optimise votre impact environnemental. <br><strong>15 points</strong>.</p></li>
      <li><p>Le fait que le produit soit issu ou non de l'agriculture biologique. S'il est bio, votre produit a été produit dans des conditions respectueuses de l'environnement. <br><strong>10 points</strong>.</p></li>
    </ol>
  </div>

</div>

app/views/pages/export.html.erb
<title><% content_for :title, "Tutti Frutti - Dites-le à vos amis sur les réseaux" %></title>

<div class="mt-4 container">
  <div class="highlight-title">
    <h6><%= @user.username.capitalize %></h6>
  </div>
  <h5 class="pt-3"><%= @user == current_user ? "Votre" : "Son" %><span class="title-score"> <strong>Le suivi</strong></span> du mois de <%= @current_month %></h5>
  <div class="text-center">
  <%= render 'shared/grades_month', score: @current_score, note: @current_note, last: @last_score, last_m: @last_month, user: @user, export: true %>
  </div>
</div>
</html>

app/views/pages/home.html.erb
<title><% content_for :title, "Tutti Frutti - Les fruits et légumes de saison" %></title>
<div class="container" style="background-image: url('<%= image_url('shape.svg')%>'); background-repeat: no-repeat; background-position: left center;">
  <div class="search-bar-home my-4 text-center">
    <h2>Rechercher un fruit ou un légume</h2>
    <%= image_tag 'sprinkle-bottom.svg', class: "stick-carousel-bottom" %>
    <%= image_tag 'sprinkle-top.svg', class: "stick-carousel-top" %>
    <%= render "shared/search_form" %>
  </div>
  <%# ---------------------  ------------- %>
  <div class="monthly-product my-3">
    <h2 class="text-center">Les fruits et légumes de </h2>
    <h2 class="month-display text-center"><%= @current_month %></h2>
    <%= render 'shared/carousel', products: @products %>
  </div>
  <%# ---------------------  ------------- %>
  <div class="text-justify my-5 ms-3 align-items-justify highlight-title">
    <h6>Pourquoi<br> consommer de saison ?</h6>
    <p>Optez pour des fruits et légumes de saison afin de bénéficier de leurs <strong>bienfaits nutritionnels</strong>, <strong>réduire l'impact écologique</strong> et <strong>encourager les circuits courts</strong> au détriment des produits importés. </p>
  </div>
    <%# ---------------------  ------------- %>
  <div class="all-monthly-product my-3 text-center">
    <h2>Tous les fruits et légumes du moment</h2>
      <div class="d-flex justify-content-around my-5">
        <div class="flex-wrap illu-menu" style="flex-basis: 150px">
          <%= link_to products_path(fruits: true), class: 'category-link text-decoration-none d-block text-center my-3',style: 'font-size: 22px' do %>
            <%= image_tag 'illu-fruits.svg', height: 120 %>
            <%= image_tag 'underline.svg', class: "underline-left" %>
            <p>Fruits</p>
          <% end %>
        </div>

        <div class="flex-wrap illu-menu" style="flex-basis: 150px">
          <%= link_to products_path(legumes: true), class: 'category-link text-decoration-none d-block text-center my-3',style: 'font-size: 22px' do %>
            <%= image_tag 'illu_veges.svg', height: 120 %>
            <%= image_tag 'underline.svg', class: "underline-right" %>
            <p>Légumes</p>
          <% end %>
        </div>
      </div>
  </div>

</div>

<div class="text-justify mt-5 align-items-justify highlight-title-bis" style="background-image: url('<%= image_url('apple.svg')%>'); background-repeat: no-repeat;
    background-position: bottom right; margin-right: -15px;">
  <div class="text-justify mt-5 mx-3 align-items-justify highlight-title-bis" >
    <h6>Pourquoi<br> acheter local ?</h6>
    <p class="pb-5 mb-0">Privilégiez les circuits courts afin d’avoir moins d’impact polluant sur la planète. Où trouver des fruits et légumes locaux ? Dans les magasins bios ou en adhérant à des coopératives de produits bios et locaux.</p>
  </div>
</div>

app/views/pages/map.html.erb
<title><% content_for :title, "Tutti Frutti - Les adresses où acheter de saison" %></title>

<div style="width: 100%; height: 100vh; margin-top: -40px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>


<!-- Modal -->
<% @stores['records'].each do |store| %>
  <div class="modal fade" id="store-modal-<%= store['recordid'] %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <% colors = ['#0B8790', '#90DBD0', '#FDCB44', '#FDB3A5', '#FC755D', '#FDE773'] %>
          <h5 class="modal-title" id="exampleModalLabel" style="color: <%= colors.sample.html_safe %>; font-weight: bold"><%= store['fields']['nom_du_commerce'].titleize %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <ul class="list-unstyled">
            <li><i class="fa-solid fa-basket-shopping pe-3 fa-sm font-icon-map"></i><%= store['fields']['type_de_commerce'].split.first %></li>
            <li><span><i class="fa-solid fa-location-dot pe-3 fa-sm font-icon-map"></i></span> <%= store['fields']['adresse'].titleize %>, <%= store['fields']['code_postal'] %></li>
            <% if  store['fields']['site_internet'] %>
              <li><i class="fa-solid fa-earth-europe pe-3 fa-sm font-icon-map"></i><strong><%= link_to store['fields']['nom_du_commerce'].titleize, store['fields']['site_internet'], target: '_blank', class: 'text-decoration-none' %></strong></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>
<!-- End Modal -->

app/views/pages/profile.html.erb
<title><% content_for :title, "Tutti Frutti - Suivi de mon impact environnemental" %></title>

<div class="container text-center py-3" style="overflow: hidden">
  <% if current_user == @user %>
    <h2 class="py-3">Bonjour <span class="user-name"><%= current_user.first_name %></span></h2>
  <% else %>
    <h2 class="py-3">Le profil de <span class="user-name"><%= @user.first_name %></span></h2>
  <% end %>

  <ul class="nav justify-content-around navbar-profile p-1" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link nav-link-profile <%= "active" if params[:tab] == "home" %>" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Score <%= @current_month %></button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link nav-link-profile <%= "active" unless params[:tab] == "home" %>" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Score Global</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link nav-link-profile" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false"><%= image_tag 'group.svg' %></button>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade  <%= "active show" if params[:tab] == "home" %>" id="home" role="tabpanel" aria-labelledby="home-tab">
      <% if @current_score.nil? %>
        <div class="motivation-speech mt-5" style="background-image: url(<%= image_path('shape-round.svg') %>)">
          <div class="motivation-content">
            <%= image_tag 'various_fruits.svg', class: 'pt-5' %>
            <h6 class="comment-score pt-3">Vous n'avez pas encore de suivi pour le mois de <%= @current_month %>.</h6>
            <p class="px-4">Commencez le dès maintenant en regardant les <%= link_to 'fruits et légumes', products_path %> du mois !</p>
          </div>
        </div>
      <% else %>
        <%= render 'shared/grades_month', score: @current_score, note: @current_note, last: @last_score, last_m: @last_month, user: @user, export: false %>
      <% end %>

    </div>

    <div class="tab-pane fade  <%= "active show" unless params[:tab] == "home" %>" id="contact" role="tabpanel" aria-labelledby="contact-tab">

      <% if @global_score.nil?%>
        <div class="motivation-speech mt-5" style="background-image: url(<%= image_path('shape-round.svg') %>)">
          <div class="motivation-content">
            <%= image_tag 'various_fruits.svg', class: 'pt-5' %>
            <h6 class="comment-score pt-3">Vous n'avez pas encore de suivi.</h6>
            <p class="px-4">Commencez le dès maintenant en regardant les <%= link_to 'fruits et légumes', products_path %> du mois !</p>
          </div>
        </div>
      <% else %>
        <%= render 'shared/grades_global', score: @global_score, note: @global_note %>
      <% end %>

    </div>

    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab" data-controller="search-complete"   data-search-complete-source-value="<%= @users %>">
    <% if @user == current_user %>
      <%= simple_form_for add_friend_path, method: 'get', class: "form-inline" do %>
        <div class="form-search search-data">
          <%= text_field_tag :query, params[:query], data: { 'search-complete-target' => 'query' }, autocomplete: :off, class: "form-control search-input", placeholder: "Ajouter un(e) ami(e)" %>
        </div>
      <% end %>
    <% end %>
      <div class="container mt-3">
        <div>
          <h3>Amis</h3>
          <div class="d-grid justify-content-center text-start mt-3">
            <% @follows.each do |follow| %>
            <% if (same = Social.find_by(asker: follow.receiver, receiver: follow.asker)) %>
            <% @follows.delete(same) %>
              <div class="card-user">
                <%= link_to follow.receiver.username, profile_path(follow.asker), class:"text-decoration-none text-danger" %>
                <p>Tutti-Amis</p>
              </div>
            <% elsif @user == follow.receiver %>
                <div class="card-user">
                  <%= link_to follow.asker.username, profile_path(follow.asker), class:"text-decoration-none text-danger" %>
                  <%= link_to "Suivre en retour", add_friend_path(query: follow.asker.username), class: "btn btn-primary text-white" %>
                  </div>
              <% else %>
                <div class="card-user">
                  <%= link_to follow.receiver.username, profile_path(follow.receiver), class:"text-decoration-none text-danger" %>
                  <p>En attente</p>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>
 <% unless @global_score.nil? || @current_score.nil? %>
    <%= link_to "https://api.apiflash.com/v1/urltoimage?access_key=55d811e6118440e2aab824cd32cc8f88&url=http%3A%2F%2Fwww.tutti-frutti.me%2Fexport%2F#{current_user.id}&width=426&height=926&full_page=true&quality=100", download: "Tutti-frutti-#{@current_month}.png" do %>
      <button class="btn btn-primary text-white mt-3">Partager mon profil</button>
    <% end %>
<% end %>

app/views/pages/welcome.html.erb
<title><% content_for :title, "Tutti Frutti - Bienvenue sur Tutti Frutti" %></title>

<div class="welcome" style="background-color: #FB7259; height: 100vh">
  <div style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)),url('<%= image_url('welcome.svg')%>'); height: 100vh; background-size: cover;background-repeat: no-repeat;background-position: left;">
    <div class="flex-column text-center" style="padding-top: 85px;">
      <h1 style="color: white;font-family: 'Inconsolata'; font-weight: 800;font-size: 48px" class="m-5">Tutti Frutti</h1><br>
      <h6 style="color: white; letter-spacing: 1px;" class="mx-5 px-5;">Découvrez le pouvoir des <br><strong style="color: white; text-shadow: -2px 3px 0px #0b8690; letter-spacing: 1px; line-height: 1.6">fruits et légumes de saison</strong></h6>

      <div class="choice d-flex flex-column w-100 px-3" style="margin-top: 50px ;">
        <% unless user_signed_in? %>
          <%= link_to 'Connexion ou inscription', user_session_path, class: 'btn-welcome py-3 mb-3'%>
        <% end %>
        <%= link_to 'Continuer', home_path, class: 'btn-welcome py-3 mb-3'%>
      </div>
    </div>
  </div>
</div>